/*
* Copyright 2025 Carlos Rodrigo Briseño Ruiz
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
import { Router } from "express";

const router = Router();

router.get(
	"/img",
	async (req, res) => {
		setTimeout(() => {
			return res.status(200).json({
				success: "later",
				imgURI: "https://www.adobe.com/cc-shared/assets/firefly/img/media_125dde3e73c0220c0112c0f7d7378a605045e0e57.jpg?width=500&format=jpg&optimize=medium",
				altText: "Generated by Adobe "
			});
		}, 100);
	}

);

export default router;
